// Generated by scripts/sync-shared.ts — do not edit.
//
// What the person chose, by id, in their own wording. The reading stores the
// label beside a change, so a change always names the thing the person picked
// rather than the model's paraphrase of it.
//
// Ids are stored in the database and must never be renamed.

export const DIRECTION_AREA_LABELS: Record<string, string> = {
  "own_way_of_working": "自分に合う働き方を見つけたい",
  "own_name_and_taste": "自分の名前・感性で仕事をしたい",
  "expertise": "専門性をつくりたい",
  "own_axis": "自分の軸で決められるようになりたい",
  "proof_i_can": "「自分ならできる」という証拠を増やしたい",
  "move_somewhere_new": "新しい場所へ動きたい",
  "connections": "人とのつながりを育てたい",
  "beyond_work": "仕事以外の大切なものも育てたい",
  "rebuild": "一度止まったところから立て直したい",
  "not_sure_yet": "まだ分からない",
};

export const DESIRED_SELF_LABELS: Record<string, string> = {
  "do_try_not_just_think": "考えるだけでなく試せる",
  "do_make_ideas_real": "アイデアを形にできる",
  "do_first_step_fast": "最初の一歩を早く出せる",
  "do_build_while_showing": "人に見せながら作れる",
  "do_more_than_once": "一度で終わらず何度か試せる",
  "do_another_way": "失敗しても別の方法を試せる",
  "know_what_i_like": "自分の好きなことが分かる",
  "know_what_im_good_at": "自分の得意が分かる",
  "know_bad_environments": "苦手な環境が分かる",
  "know_when_i_have_energy": "力が出る条件が分かる",
  "know_what_matters": "自分が大切にしたいことが分かる",
  "know_next_direction": "次に向かいたい方向が分かる",
  "choose_decide_myself": "自分で決められる",
  "choose_decline": "合わないものを断れる",
  "choose_not_to_do": "やらないことを選べる",
  "choose_without_comparing": "他人と比較せず選べる",
  "choose_change_direction": "方向転換できる",
  "choose_with_conviction": "納得して選べる",
  "express_say_my_thoughts": "自分の考えを言える",
  "express_show_ideas": "人にアイデアを見せられる",
  "express_publish_work": "自分の作品を外に出せる",
  "express_to_strangers": "初対面の人にも説明できる",
  "express_under_my_name": "自分の名前で何かできる",
  "connect_ask_advice": "相談できる",
  "connect_ask_for_help": "助けを求められる",
  "connect_try_together": "一緒に挑戦できる人がいる",
  "connect_be_myself": "自分らしくいられる人がいる",
  "connect_widen_world": "自分の世界を広げてくれる人と出会う",
  "live_more_fun": "楽しい時間が増える",
  "live_absorbed_in_something": "夢中になれるものがある",
  "live_protect_my_time": "自分の時間を守れる",
  "live_beyond_work": "仕事以外にも大切なものがある",
  "live_be_moved": "心が動く経験を増やせる",
};
