-- crincran — demo data.
--
-- Generated by scripts/build-demo-sql.mjs from supabase/demo/*.tsv. Edit the
-- TSVs and re-run; do not edit this file.
--
-- 80 records, 2026 to 2026, plus the lens they were
-- recorded under. Nothing else: no analysis, no progressions, no month
-- readings. Those are what the app produces from evidence, and writing them
-- here would be inventing the very thing the demo is meant to show it finding.
--
-- Row ids are derived from the account's own id, so loading twice replaces the
-- same 80 rows instead of doubling them, and demo rows can never collide
-- with real ones.
--
-- __DEMO_EMAIL__ is replaced by .github/workflows/load-demo-data.yml.

do $$
declare
  uid uuid;
  demo record;
  inserted integer := 0;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  -- The lens, one row per year the records span. Same choices each year: the
  -- spreadsheet asserts one direction, not a change of direction.
  insert into public.year_directions (user_id, year, selected_areas, desired_self_cards)
  select uid, y, array['own_way_of_working', 'own_name_and_taste', 'own_axis', 'move_somewhere_new', 'connections'], array['do_try_not_just_think', 'do_make_ideas_real', 'do_build_while_showing', 'do_another_way', 'know_what_i_like', 'know_when_i_have_energy', 'know_next_direction', 'choose_decide_myself', 'choose_decline', 'choose_change_direction', 'express_say_my_thoughts', 'express_show_ideas', 'express_under_my_name', 'connect_ask_advice', 'connect_try_together', 'live_more_fun', 'live_absorbed_in_something']
    from unnest(array[2026]) as y
  -- Never over a direction the person actually built: a row that already has
  -- a theme or lenses is theirs, and the demo leaves it alone.
  on conflict (user_id, year) do update
     set selected_areas = excluded.selected_areas,
         desired_self_cards = excluded.desired_self_cards
   where public.year_directions.initial_theme is null
     and public.year_directions.progression_lenses = '{}';

  for demo in
    select * from (values
    ('LOG-0401', '2026-05-01', '2026-05-01T21:00:00+09:00', 'self_action', array['tried'], '仕事のあとに自分が担当したい役割を言語化。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0402', '2026-05-02', '2026-05-02T21:01:00+09:00', 'thought', array['friction'], '複数部署の調整をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0403', '2026-05-04', '2026-05-04T21:02:00+09:00', 'relationship', array['enjoyed'], '参加者と次回案を話す。話しているうちに時間を忘れていた。'),
    ('LOG-0404', '2026-05-05', '2026-05-05T21:03:00+09:00', 'self_action', array['first_time', 'tried'], 'イベントの振り返り会。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0405', '2026-05-07', '2026-05-07T21:04:00+09:00', 'thought', array['discovered'], '今日ふと、自分は実務を全部抱えるより、企画して人をつなぐ時に力が出るのかもしれないと思った。'),
    ('LOG-0406', '2026-05-08', '2026-05-08T21:05:00+09:00', 'self_action', array['enjoyed'], '人と人をつないで企画を前に進める時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0407', '2026-05-10', '2026-05-10T21:06:00+09:00', 'relationship', array['friction'], '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0408', '2026-05-11', '2026-05-11T21:07:00+09:00', 'thought', array['enjoyed', 'discovered'], '人と人をつないで企画を前に進める時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0409', '2026-05-13', '2026-05-13T21:08:00+09:00', 'self_action', array['changed'], '自分が担当したい役割を言語化の進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0410', '2026-05-14', '2026-05-14T21:09:00+09:00', 'relationship', array['tried'], '参加者と次回案を話す時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0411', '2026-05-16', '2026-05-16T21:10:00+09:00', 'thought', array['friction', 'discovered'], '複数部署の調整のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0412', '2026-05-17', '2026-05-17T21:11:00+09:00', 'self_action', array['self_decided'], '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0413', '2026-05-19', '2026-05-19T21:12:00+09:00', 'relationship', array['first_time'], 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0414', '2026-05-20', '2026-05-20T21:13:00+09:00', 'self_action', array['friction'], '自分が担当したい役割を言語化を進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0415', '2026-05-22', '2026-05-22T21:14:00+09:00', 'thought', array['discovered'], '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0416', '2026-05-23', '2026-05-23T21:15:00+09:00', 'relationship', array['enjoyed', 'tried'], '参加者と次回案を話す時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0417', '2026-05-25', '2026-05-25T21:16:00+09:00', 'self_action', array['tried', 'changed'], '自分が担当したい役割を言語化を前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0418', '2026-05-26', '2026-05-26T21:17:00+09:00', 'thought', array['friction'], '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0419', '2026-05-27', '2026-05-27T21:18:00+09:00', 'relationship', array['discovered'], '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0420', '2026-05-28', '2026-05-28T21:19:00+09:00', 'self_action', array['self_decided', 'tried'], '今週は人と人をつないで企画を前に進める時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。'),
    ('LOG-0421', '2026-06-01', '2026-06-01T21:20:00+09:00', 'self_action', array['tried'], '仕事のあとに転職・副業・現職継続の3案を並べる。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0422', '2026-06-02', '2026-06-02T21:21:00+09:00', 'thought', array['friction'], '新しい担当の打診をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0423', '2026-06-04', '2026-06-04T21:22:00+09:00', 'relationship', array['enjoyed'], '別会社の人に働き方を聞く。話しているうちに時間を忘れていた。'),
    ('LOG-0424', '2026-06-05', '2026-06-05T21:23:00+09:00', 'self_action', array['first_time', 'tried'], '2社のカジュアル面談と副業相談。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0425', '2026-06-07', '2026-06-07T21:24:00+09:00', 'thought', array['discovered'], '今日ふと、二択ではなく、小さく試してから選べるのかもしれないと思った。'),
    ('LOG-0426', '2026-06-08', '2026-06-08T21:25:00+09:00', 'self_action', array['enjoyed'], '選択肢を比較して仮説を立てる時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0427', '2026-06-10', '2026-06-10T21:26:00+09:00', 'relationship', array['friction'], '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0428', '2026-06-11', '2026-06-11T21:27:00+09:00', 'thought', array['enjoyed', 'discovered'], '選択肢を比較して仮説を立てる時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0429', '2026-06-13', '2026-06-13T21:28:00+09:00', 'self_action', array['changed'], '転職・副業・現職継続の3案を並べるの進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0430', '2026-06-14', '2026-06-14T21:29:00+09:00', 'relationship', array['tried'], '別会社の人に働き方を聞く時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0431', '2026-06-16', '2026-06-16T21:30:00+09:00', 'thought', array['friction', 'discovered'], '新しい担当の打診のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0432', '2026-06-17', '2026-06-17T21:31:00+09:00', 'self_action', array['self_decided'], '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0433', '2026-06-19', '2026-06-19T21:32:00+09:00', 'relationship', array['first_time'], 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0434', '2026-06-20', '2026-06-20T21:33:00+09:00', 'self_action', array['friction'], '転職・副業・現職継続の3案を並べるを進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0435', '2026-06-22', '2026-06-22T21:34:00+09:00', 'thought', array['discovered'], '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0436', '2026-06-23', '2026-06-23T21:35:00+09:00', 'relationship', array['enjoyed', 'tried'], '別会社の人に働き方を聞く時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0437', '2026-06-25', '2026-06-25T21:36:00+09:00', 'self_action', array['tried', 'changed'], '転職・副業・現職継続の3案を並べるを前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0438', '2026-06-26', '2026-06-26T21:37:00+09:00', 'thought', array['friction'], '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0439', '2026-06-27', '2026-06-27T21:38:00+09:00', 'relationship', array['discovered'], '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0440', '2026-06-28', '2026-06-28T21:39:00+09:00', 'self_action', array['self_decided', 'tried'], '今週は選択肢を比較して仮説を立てる時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。'),
    ('LOG-0441', '2026-07-01', '2026-07-01T21:40:00+09:00', 'self_action', array['tried'], '仕事のあとに次の環境で譲れない条件を決める。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0442', '2026-07-02', '2026-07-02T21:41:00+09:00', 'thought', array['friction'], '昇進可能性の話をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0443', '2026-07-04', '2026-07-04T21:42:00+09:00', 'relationship', array['enjoyed'], '信頼する友人に選択基準を話す。話しているうちに時間を忘れていた。'),
    ('LOG-0444', '2026-07-05', '2026-07-05T21:43:00+09:00', 'self_action', array['first_time', 'tried'], '候補先のチームと面談。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0445', '2026-07-07', '2026-07-07T21:44:00+09:00', 'thought', array['discovered'], '今日ふと、給与だけでなく、裁量・意味・一緒に働く人を重視したいのかもしれないと思った。'),
    ('LOG-0446', '2026-07-08', '2026-07-08T21:45:00+09:00', 'self_action', array['enjoyed'], '自分の基準で選択肢を整理する時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0447', '2026-07-10', '2026-07-10T21:46:00+09:00', 'relationship', array['friction'], '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0448', '2026-07-11', '2026-07-11T21:47:00+09:00', 'thought', array['enjoyed', 'discovered'], '自分の基準で選択肢を整理する時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0449', '2026-07-13', '2026-07-13T21:48:00+09:00', 'self_action', array['changed'], '次の環境で譲れない条件を決めるの進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0450', '2026-07-14', '2026-07-14T21:49:00+09:00', 'relationship', array['tried'], '信頼する友人に選択基準を話す時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0451', '2026-07-16', '2026-07-16T21:50:00+09:00', 'thought', array['friction', 'discovered'], '昇進可能性の話のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0452', '2026-07-17', '2026-07-17T21:51:00+09:00', 'self_action', array['self_decided'], '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0453', '2026-07-19', '2026-07-19T21:52:00+09:00', 'relationship', array['first_time'], 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0454', '2026-07-20', '2026-07-20T21:53:00+09:00', 'self_action', array['friction'], '次の環境で譲れない条件を決めるを進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0455', '2026-07-22', '2026-07-22T21:54:00+09:00', 'thought', array['discovered'], '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0456', '2026-07-23', '2026-07-23T21:55:00+09:00', 'relationship', array['enjoyed', 'tried'], '信頼する友人に選択基準を話す時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0457', '2026-07-25', '2026-07-25T21:56:00+09:00', 'self_action', array['tried', 'changed'], '次の環境で譲れない条件を決めるを前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0458', '2026-07-26', '2026-07-26T21:57:00+09:00', 'thought', array['friction'], '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0459', '2026-07-27', '2026-07-27T21:58:00+09:00', 'relationship', array['discovered'], '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0460', '2026-07-28', '2026-07-28T21:59:00+09:00', 'self_action', array['self_decided', 'tried'], '今週は自分の基準で選択肢を整理する時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。'),
    ('LOG-0461', '2026-08-01', '2026-08-01T21:00:00+09:00', 'self_action', array['tried'], '仕事のあとに次の半年で試す選択を一つ決める。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0462', '2026-08-02', '2026-08-02T21:01:00+09:00', 'thought', array['friction'], '現職での役割調整をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0463', '2026-08-04', '2026-08-04T21:02:00+09:00', 'relationship', array['enjoyed'], '関係者に今後の希望を伝える。話しているうちに時間を忘れていた。'),
    ('LOG-0464', '2026-08-05', '2026-08-05T21:03:00+09:00', 'self_action', array['first_time', 'tried'], '新しいプロジェクトへの参加を決める。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0465', '2026-08-07', '2026-08-07T21:04:00+09:00', 'thought', array['discovered'], '今日ふと、不安がなくなるのを待つより、Evidenceがある方向を小さく選びたいのかもしれないと思った。'),
    ('LOG-0466', '2026-08-08', '2026-08-08T21:05:00+09:00', 'self_action', array['enjoyed'], 'これまでの記録を見ながら次を考える時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0467', '2026-08-10', '2026-08-10T21:06:00+09:00', 'relationship', array['friction'], '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0468', '2026-08-11', '2026-08-11T21:07:00+09:00', 'thought', array['enjoyed', 'discovered'], 'これまでの記録を見ながら次を考える時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0469', '2026-08-13', '2026-08-13T21:08:00+09:00', 'self_action', array['changed'], '次の半年で試す選択を一つ決めるの進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0470', '2026-08-14', '2026-08-14T21:09:00+09:00', 'relationship', array['tried'], '関係者に今後の希望を伝える時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0471', '2026-08-16', '2026-08-16T21:10:00+09:00', 'thought', array['friction', 'discovered'], '現職での役割調整のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0472', '2026-08-17', '2026-08-17T21:11:00+09:00', 'self_action', array['self_decided'], '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0473', '2026-08-19', '2026-08-19T21:12:00+09:00', 'relationship', array['first_time'], 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0474', '2026-08-20', '2026-08-20T21:13:00+09:00', 'self_action', array['friction'], '次の半年で試す選択を一つ決めるを進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0475', '2026-08-22', '2026-08-22T21:14:00+09:00', 'thought', array['discovered'], '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0476', '2026-08-23', '2026-08-23T21:15:00+09:00', 'relationship', array['enjoyed', 'tried'], '関係者に今後の希望を伝える時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0477', '2026-08-25', '2026-08-25T21:16:00+09:00', 'self_action', array['tried', 'changed'], '次の半年で試す選択を一つ決めるを前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0478', '2026-08-26', '2026-08-26T21:17:00+09:00', 'thought', array['friction'], '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0479', '2026-08-27', '2026-08-27T21:18:00+09:00', 'relationship', array['discovered'], '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0480', '2026-08-28', '2026-08-28T21:19:00+09:00', 'self_action', array['self_decided', 'tried'], '今週はこれまでの記録を見ながら次を考える時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。')
    ) as t(key, occurred_on, occurred_at, log_type, moment_tags, body)
  loop
    insert into public.logs
      (id, user_id, occurred_on, occurred_at, type, moment_tags, optional_answer)
    values (
      md5(uid::text || ':crincran-demo:' || demo.key)::uuid,
      uid,
      demo.occurred_on::date,
      demo.occurred_at::timestamptz,
      demo.log_type::public.log_type,
      demo.moment_tags::public.moment_tag[],
      demo.body
    )
    on conflict (id) do update
       set occurred_on = excluded.occurred_on,
           occurred_at = excluded.occurred_at,
           type = excluded.type,
           moment_tags = excluded.moment_tags,
           optional_answer = excluded.optional_answer;
    inserted := inserted + 1;
  end loop;

  raise notice 'crincran demo: % records for %', inserted, '__DEMO_EMAIL__';
end $$;
