-- crincran — demo data.
--
-- Generated by scripts/build-demo-sql.ts from supabase/demo/*.tsv. Edit the
-- TSVs and re-run; do not edit this file.
--
-- 20 records, 2026 to 2026, plus the lens and the declarations they were
-- recorded under. Nothing else: no analysis, no progressions, no month
-- readings. Those are what the app produces from evidence, and writing them
-- here would be inventing the very thing the demo is meant to show it finding.
--
-- Row ids are derived from the account's own id, so loading twice replaces the
-- same 20 rows instead of doubling them, and demo rows can never collide
-- with real ones.
--
-- __DEMO_EMAIL__ is replaced by .github/workflows/load-demo-data.yml.

do $$
declare
  uid uuid;
  demo record;
  inserted integer := 0;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  -- The year's declaration. One row per year the records span; it is a
  -- heading, not a target, and the year-end reading compares against it.
  insert into public.year_directions (user_id, year, initial_theme)
  select uid, y, t.theme
    from unnest(
      array[2026],
      array['自分の基準で、次の働き方を選ぶ']::text[]
    ) as t(y, theme)
  -- Never over a declaration the person made. The theme the demo writes is
  -- its own, which is also why the update below cannot reach theirs.
  on conflict (user_id, year) do update
     set initial_theme = excluded.initial_theme
   where public.year_directions.initial_theme is null;

  -- The month's declaration and its antennas. The antennas are the lens: at
  -- most two, chosen at the start of the month, and what the composer offers
  -- categories from. Source is custom because the person wrote the theme
  -- rather than taking one of the three the model offered — there was no
  -- month before it to base a candidate on.
  insert into public.month_themes
    (user_id, year, month, initial_theme, source, antenna_ids)
  select uid, m.year, m.month, m.theme, 'custom', m.antennas
    from (values
      (2026, 9, '次の一歩を選ぶ', array['progress', 'self_understanding'])
    ) as m(year, month, theme, antennas)
  on conflict (user_id, year, month) do update
     set initial_theme = excluded.initial_theme,
         source = excluded.source,
         antenna_ids = excluded.antenna_ids
   where public.month_themes.initial_theme is null
     and public.month_themes.final_theme is null;

  for demo in
    select * from (values
    ('LOG-0461', '2026-09-01', '2026-09-01T21:00:00+09:00', 'progress_tried', 'tested', '仕事のあとに次の半年で試す選択を一つ決める。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0462', '2026-09-02', '2026-09-02T21:01:00+09:00', 'self_hard', 'role', '現職での役割調整をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0463', '2026-09-04', '2026-09-04T21:02:00+09:00', 'self_fun', 'people', '関係者に今後の希望を伝える。話しているうちに時間を忘れていた。'),
    ('LOG-0464', '2026-09-05', '2026-09-05T21:03:00+09:00', 'progress_did', 'first_time', '新しいプロジェクトへの参加を決める。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0465', '2026-09-07', '2026-09-07T21:04:00+09:00', 'progress_learned', 'next', '今日ふと、不安がなくなるのを待つより、Evidenceがある方向を小さく選びたいのかもしれないと思った。'),
    ('LOG-0466', '2026-09-08', '2026-09-08T21:05:00+09:00', 'self_fun', 'activity', 'これまでの記録を見ながら次を考える時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0467', '2026-09-10', '2026-09-10T21:06:00+09:00', 'self_hard', 'autonomy', '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0468', '2026-09-11', '2026-09-11T21:07:00+09:00', 'self_fun', 'time_use', 'これまでの記録を見ながら次を考える時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0469', '2026-09-13', '2026-09-13T21:08:00+09:00', 'progress_learned', 'method', '次の半年で試す選択を一つ決めるの進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0470', '2026-09-14', '2026-09-14T21:09:00+09:00', 'progress_tried', 'talked', '関係者に今後の希望を伝える時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0471', '2026-09-16', '2026-09-16T21:10:00+09:00', 'self_hard', 'autonomy', '現職での役割調整のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0472', '2026-09-17', '2026-09-17T21:11:00+09:00', 'progress_did', 'took_action', '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0473', '2026-09-19', '2026-09-19T21:12:00+09:00', 'progress_tried', 'talked', 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0474', '2026-09-20', '2026-09-20T21:13:00+09:00', 'self_hard', 'activity', '次の半年で試す選択を一つ決めるを進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0475', '2026-09-22', '2026-09-22T21:14:00+09:00', 'progress_learned', 'strength', '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0476', '2026-09-23', '2026-09-23T21:15:00+09:00', 'self_fun', 'people', '関係者に今後の希望を伝える時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0477', '2026-09-25', '2026-09-25T21:16:00+09:00', 'progress_tried', 'tested', '次の半年で試す選択を一つ決めるを前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0478', '2026-09-26', '2026-09-26T21:17:00+09:00', 'self_hard', 'environment', '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0479', '2026-09-27', '2026-09-27T21:18:00+09:00', 'progress_learned', 'relationships', '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0480', '2026-09-28', '2026-09-28T21:19:00+09:00', 'progress_did', 'took_action', '今週はこれまでの記録を見ながら次を考える時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。')
    ) as t(key, occurred_on, occurred_at, category_id, detail_id, body)
  loop
    insert into public.logs
      (id, user_id, occurred_on, occurred_at, category_id, detail_id, body,
       input_method, classification_source, classification_status)
    values (
      md5(uid::text || ':crincran-demo:' || demo.key)::uuid,
      uid,
      demo.occurred_on::date,
      demo.occurred_at::timestamptz,
      demo.category_id,
      demo.detail_id,
      demo.body,
      'category'::public.log_input_method,
      'user'::public.classification_source,
      'confirmed'::public.classification_status
    )
    on conflict (id) do update
       set occurred_on = excluded.occurred_on,
           occurred_at = excluded.occurred_at,
           category_id = excluded.category_id,
           detail_id = excluded.detail_id,
           body = excluded.body;
    inserted := inserted + 1;
  end loop;

  raise notice 'crincran demo: % records for %', inserted, '__DEMO_EMAIL__';
end $$;
