-- crincran — remove the demo data.
--
-- Generated by scripts/build-demo-sql.mjs. Deletes the 20 demo records and
-- the years' lens rows, and nothing else: the ids are derived the same way
-- they were written, so a record the person made themselves cannot match.

do $$
declare
  uid uuid;
  removed integer;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  delete from public.logs
   where user_id = uid
     and id in (
       select md5(uid::text || ':crincran-demo:' || key)::uuid
         from unnest(array['LOG-0461', 'LOG-0462', 'LOG-0463', 'LOG-0464', 'LOG-0465', 'LOG-0466', 'LOG-0467', 'LOG-0468', 'LOG-0469', 'LOG-0470', 'LOG-0471', 'LOG-0472', 'LOG-0473', 'LOG-0474', 'LOG-0475', 'LOG-0476', 'LOG-0477', 'LOG-0478', 'LOG-0479', 'LOG-0480']) as key
     );
  get diagnostics removed = row_count;

  -- Only the rows the demo itself wrote. A theme the demo did not write, a
  -- final theme, or a lens means the row is the person's own, and it stays.
  delete from public.month_themes
   where user_id = uid
     and (year, month) in ((2026, 9))
     and final_theme is null
     and initial_theme in ('次の一歩を選ぶ');

  delete from public.year_directions
   where user_id = uid
     and year = any(array[2026])
     and (initial_theme is null
          or initial_theme in ('自分の基準で、次の働き方を選ぶ'))
     and final_theme is null
     and progression_lenses = '{}';

  raise notice 'crincran demo: removed % records for %', removed, '__DEMO_EMAIL__';
end $$;
