-- crincran — remove the demo data.
--
-- Generated by scripts/build-demo-sql.mjs. Deletes the 80 demo records and
-- the years' lens rows, and nothing else: the ids are derived the same way
-- they were written, so a record the person made themselves cannot match.

do $$
declare
  uid uuid;
  removed integer;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  delete from public.logs
   where user_id = uid
     and id in (
       select md5(uid::text || ':crincran-demo:' || key)::uuid
         from unnest(array['LOG-0401', 'LOG-0402', 'LOG-0403', 'LOG-0404', 'LOG-0405', 'LOG-0406', 'LOG-0407', 'LOG-0408', 'LOG-0409', 'LOG-0410', 'LOG-0411', 'LOG-0412', 'LOG-0413', 'LOG-0414', 'LOG-0415', 'LOG-0416', 'LOG-0417', 'LOG-0418', 'LOG-0419', 'LOG-0420', 'LOG-0421', 'LOG-0422', 'LOG-0423', 'LOG-0424', 'LOG-0425', 'LOG-0426', 'LOG-0427', 'LOG-0428', 'LOG-0429', 'LOG-0430', 'LOG-0431', 'LOG-0432', 'LOG-0433', 'LOG-0434', 'LOG-0435', 'LOG-0436', 'LOG-0437', 'LOG-0438', 'LOG-0439', 'LOG-0440', 'LOG-0441', 'LOG-0442', 'LOG-0443', 'LOG-0444', 'LOG-0445', 'LOG-0446', 'LOG-0447', 'LOG-0448', 'LOG-0449', 'LOG-0450', 'LOG-0451', 'LOG-0452', 'LOG-0453', 'LOG-0454', 'LOG-0455', 'LOG-0456', 'LOG-0457', 'LOG-0458', 'LOG-0459', 'LOG-0460', 'LOG-0461', 'LOG-0462', 'LOG-0463', 'LOG-0464', 'LOG-0465', 'LOG-0466', 'LOG-0467', 'LOG-0468', 'LOG-0469', 'LOG-0470', 'LOG-0471', 'LOG-0472', 'LOG-0473', 'LOG-0474', 'LOG-0475', 'LOG-0476', 'LOG-0477', 'LOG-0478', 'LOG-0479', 'LOG-0480']) as key
     );
  get diagnostics removed = row_count;

  -- Only the rows the demo itself wrote. Once a theme or a lens exists the
  -- row is the person's own and is left where it is.
  delete from public.year_directions
   where user_id = uid
     and year = any(array[2026])
     and initial_theme is null
     and final_theme is null
     and progression_lenses = '{}';

  raise notice 'crincran demo: removed % records for %', removed, '__DEMO_EMAIL__';
end $$;
