-- crincran — demo data.
--
-- Generated by scripts/build-demo-sql.mjs from supabase/demo/*.tsv. Edit the
-- TSVs and re-run; do not edit this file.
--
-- 20 records, 2026 to 2026, plus the lens they were
-- recorded under. Nothing else: no analysis, no progressions, no month
-- readings. Those are what the app produces from evidence, and writing them
-- here would be inventing the very thing the demo is meant to show it finding.
--
-- Row ids are derived from the account's own id, so loading twice replaces the
-- same 20 rows instead of doubling them, and demo rows can never collide
-- with real ones.
--
-- __DEMO_EMAIL__ is replaced by .github/workflows/load-demo-data.yml.

do $$
declare
  uid uuid;
  demo record;
  inserted integer := 0;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  -- The lens, one row per year the records span. Same choices each year: the
  -- spreadsheet asserts one direction, not a change of direction.
  insert into public.year_directions (user_id, year, selected_areas, desired_self_cards)
  select uid, y, array['own_way_of_working', 'own_name_and_taste', 'own_axis', 'move_somewhere_new', 'connections'], array['do_try_not_just_think', 'do_make_ideas_real', 'do_build_while_showing', 'do_another_way', 'know_what_i_like', 'know_when_i_have_energy', 'know_next_direction', 'choose_decide_myself', 'choose_decline', 'choose_change_direction', 'express_say_my_thoughts', 'express_show_ideas', 'express_under_my_name', 'connect_ask_advice', 'connect_try_together', 'live_more_fun', 'live_absorbed_in_something']
    from unnest(array[2026]) as y
  -- Never over a direction the person actually built: a row that already has
  -- a theme or lenses is theirs, and the demo leaves it alone.
  on conflict (user_id, year) do update
     set selected_areas = excluded.selected_areas,
         desired_self_cards = excluded.desired_self_cards
   where public.year_directions.initial_theme is null
     and public.year_directions.progression_lenses = '{}';

  for demo in
    select * from (values
    ('LOG-0461', '2026-09-01', '2026-09-01T21:00:00+09:00', 'self_action', array['tried'], '仕事のあとに次の半年で試す選択を一つ決める。少しだけでも手を動かすと、考えているだけの時より気持ちが落ち着いた。'),
    ('LOG-0462', '2026-09-02', '2026-09-02T21:01:00+09:00', 'thought', array['friction'], '現職での役割調整をしていて少しモヤモヤ。何が嫌なのかはまだうまく言えない。'),
    ('LOG-0463', '2026-09-04', '2026-09-04T21:02:00+09:00', 'relationship', array['enjoyed'], '関係者に今後の希望を伝える。話しているうちに時間を忘れていた。'),
    ('LOG-0464', '2026-09-05', '2026-09-05T21:03:00+09:00', 'self_action', array['first_time', 'tried'], '新しいプロジェクトへの参加を決める。やる前は少し緊張したけれど、行ってみたら思ったより普通にできた。'),
    ('LOG-0465', '2026-09-07', '2026-09-07T21:04:00+09:00', 'thought', array['discovered'], '今日ふと、不安がなくなるのを待つより、Evidenceがある方向を小さく選びたいのかもしれないと思った。'),
    ('LOG-0466', '2026-09-08', '2026-09-08T21:05:00+09:00', 'self_action', array['enjoyed'], 'これまでの記録を見ながら次を考える時間がかなり楽しかった。予定より長くやってしまった。'),
    ('LOG-0467', '2026-09-10', '2026-09-10T21:06:00+09:00', 'relationship', array['friction'], '会議で自分の案を最後まで説明する前に話が決まってしまって、少し置いていかれた感じがした。'),
    ('LOG-0468', '2026-09-11', '2026-09-11T21:07:00+09:00', 'thought', array['enjoyed', 'discovered'], 'これまでの記録を見ながら次を考える時間は、疲れていても不思議とやめたくならない。こういう時間は覚えておきたい。'),
    ('LOG-0469', '2026-09-13', '2026-09-13T21:08:00+09:00', 'self_action', array['changed'], '次の半年で試す選択を一つ決めるの進め方を少し変えた。前より小さく区切って試すことにした。'),
    ('LOG-0470', '2026-09-14', '2026-09-14T21:09:00+09:00', 'relationship', array['tried'], '関係者に今後の希望を伝える時に、普段なら黙るところで自分の考えも一つ言ってみた。'),
    ('LOG-0471', '2026-09-16', '2026-09-16T21:10:00+09:00', 'thought', array['friction', 'discovered'], '現職での役割調整のあと、単に忙しいというより『自分で決められない』時に消耗している気がした。'),
    ('LOG-0472', '2026-09-17', '2026-09-17T21:11:00+09:00', 'self_action', array['self_decided'], '今日は頼まれたことを全部引き受けず、優先するものを自分で決めた。少し不安だけど納得感はある。'),
    ('LOG-0473', '2026-09-19', '2026-09-19T21:12:00+09:00', 'relationship', array['first_time'], 'これまであまり話したことのない人に、自分が最近考えていることを少し話した。'),
    ('LOG-0474', '2026-09-20', '2026-09-20T21:13:00+09:00', 'self_action', array['friction'], '次の半年で試す選択を一つ決めるを進めようとしたけど、思ったよりまとまらなかった。今日は無理に答えを出さずに残す。'),
    ('LOG-0475', '2026-09-22', '2026-09-22T21:14:00+09:00', 'thought', array['discovered'], '『何が正解か』より、『どの状態なら自分が動きやすいか』を見た方がよさそうだと思った。'),
    ('LOG-0476', '2026-09-23', '2026-09-23T21:15:00+09:00', 'relationship', array['enjoyed', 'tried'], '関係者に今後の希望を伝える時、相手の反応を見ながら話を広げるのが楽しかった。'),
    ('LOG-0477', '2026-09-25', '2026-09-25T21:16:00+09:00', 'self_action', array['tried', 'changed'], '次の半年で試す選択を一つ決めるを前回と違うやり方で試した。完成させてからではなく、途中の状態で一度止めて見直した。'),
    ('LOG-0478', '2026-09-26', '2026-09-26T21:17:00+09:00', 'thought', array['friction'], '周りの人の転職や昇進を見ると焦る。でも、自分が本当に欲しいものが同じなのかは分からない。'),
    ('LOG-0479', '2026-09-27', '2026-09-27T21:18:00+09:00', 'relationship', array['discovered'], '誰かに話すと、自分だけで考えていた時より何に引っかかっているかがはっきりする。'),
    ('LOG-0480', '2026-09-28', '2026-09-28T21:19:00+09:00', 'self_action', array['self_decided', 'tried'], '今週はこれまでの記録を見ながら次を考える時間を優先すると決めて、予定を少し空けた。自分で選んだ時間だと思うと集中しやすかった。')
    ) as t(key, occurred_on, occurred_at, log_type, moment_tags, body)
  loop
    insert into public.logs
      (id, user_id, occurred_on, occurred_at, type, moment_tags, optional_answer)
    values (
      md5(uid::text || ':crincran-demo:' || demo.key)::uuid,
      uid,
      demo.occurred_on::date,
      demo.occurred_at::timestamptz,
      demo.log_type::public.log_type,
      demo.moment_tags::public.moment_tag[],
      demo.body
    )
    on conflict (id) do update
       set occurred_on = excluded.occurred_on,
           occurred_at = excluded.occurred_at,
           type = excluded.type,
           moment_tags = excluded.moment_tags,
           optional_answer = excluded.optional_answer;
    inserted := inserted + 1;
  end loop;

  raise notice 'crincran demo: % records for %', inserted, '__DEMO_EMAIL__';
end $$;
