-- crincran — remove everything in an account EXCEPT the demo records.
--
-- Generated by scripts/build-demo-sql.mjs.
--
-- DESTRUCTIVE and not undoable: this deletes records the person wrote. Run it
-- only on an account meant to hold nothing but the demo.
--
-- What goes: every log that is not one of the 80 demo rows, everything that
-- hangs off those logs (analysis, evidence links — all cascade), any
-- progression left with no evidence behind it, and the month and year
-- readings. Those readings described a set of records that no longer exists,
-- and a reading nothing supports is worse than no reading.
--
-- What stays: the 80 demo records, the year's direction, and the month
-- themes — choices the person made, rather than things worked out from
-- evidence.

do $$
declare
  uid uuid;
  demo uuid[];
  removed_logs integer;
  removed_progressions integer;
begin
  select id into uid from auth.users where lower(email) = lower('__DEMO_EMAIL__');
  if uid is null then
    raise exception 'このメールアドレスのアカウントが見つかりません: %', '__DEMO_EMAIL__';
  end if;

  select array_agg(md5(uid::text || ':crincran-demo:' || key)::uuid)
    into demo
    from unnest(array['LOG-0401', 'LOG-0402', 'LOG-0403', 'LOG-0404', 'LOG-0405', 'LOG-0406', 'LOG-0407', 'LOG-0408', 'LOG-0409', 'LOG-0410', 'LOG-0411', 'LOG-0412', 'LOG-0413', 'LOG-0414', 'LOG-0415', 'LOG-0416', 'LOG-0417', 'LOG-0418', 'LOG-0419', 'LOG-0420', 'LOG-0421', 'LOG-0422', 'LOG-0423', 'LOG-0424', 'LOG-0425', 'LOG-0426', 'LOG-0427', 'LOG-0428', 'LOG-0429', 'LOG-0430', 'LOG-0431', 'LOG-0432', 'LOG-0433', 'LOG-0434', 'LOG-0435', 'LOG-0436', 'LOG-0437', 'LOG-0438', 'LOG-0439', 'LOG-0440', 'LOG-0441', 'LOG-0442', 'LOG-0443', 'LOG-0444', 'LOG-0445', 'LOG-0446', 'LOG-0447', 'LOG-0448', 'LOG-0449', 'LOG-0450', 'LOG-0451', 'LOG-0452', 'LOG-0453', 'LOG-0454', 'LOG-0455', 'LOG-0456', 'LOG-0457', 'LOG-0458', 'LOG-0459', 'LOG-0460', 'LOG-0461', 'LOG-0462', 'LOG-0463', 'LOG-0464', 'LOG-0465', 'LOG-0466', 'LOG-0467', 'LOG-0468', 'LOG-0469', 'LOG-0470', 'LOG-0471', 'LOG-0472', 'LOG-0473', 'LOG-0474', 'LOG-0475', 'LOG-0476', 'LOG-0477', 'LOG-0478', 'LOG-0479', 'LOG-0480']) as key;

  delete from public.logs
   where user_id = uid
     and not (id = any(demo));
  get diagnostics removed_logs = row_count;

  -- The evidence rows went with the logs. A progression with none left is not
  -- a progression any more: a trail is its points.
  delete from public.progressions p
   where p.user_id = uid
     and not exists (
       select 1 from public.progression_evidence e where e.progression_id = p.id
     );
  get diagnostics removed_progressions = row_count;

  delete from public.month_reviews where user_id = uid;
  delete from public.year_reviews where user_id = uid;

  raise notice 'crincran purge: % logs, % progressions removed for %',
    removed_logs, removed_progressions, '__DEMO_EMAIL__';
end $$;
