#!/usr/bin/env tsx
/**
 * Copies what the app and the Edge Functions must agree on into the Deno
 * runtime.
 *
 * The functions cannot import from `src/`, and these must not drift. Two of
 * the three are straight copies; the third is generated, because the labels
 * live inside data structures the app uses for rendering and the functions
 * only need the id-to-label mapping.
 *
 * A test compares each copy with its source. If they ever disagree, the app
 * and the reading could describe the same thing differently — and for the
 * targets in particular, a stale label would attach a change to wording the
 * person never chose.
 */
import { copyFileSync, writeFileSync } from 'node:fs';

import { DIRECTION_AREAS } from '../src/constants/areas';
import { DESIRED_SELF_CARDS } from '../src/constants/desiredSelf';

const COPIES: ReadonlyArray<readonly [string, string]> = [
  ['src/ai/progressionRules.ts', 'supabase/functions/_shared/progressionRules.ts'],
  ['src/ai/changeRules.ts', 'supabase/functions/_shared/changeRules.ts'],
];

for (const [source, target] of COPIES) {
  copyFileSync(source, target);
  console.log(`synced ${source} -> ${target}`);
}

const entries = (pairs: ReadonlyArray<readonly [string, string]>): string =>
  pairs.map(([id, label]) => `  ${JSON.stringify(id)}: ${JSON.stringify(label)},`).join('\n');

const TARGETS = 'supabase/functions/_shared/targets.ts';
writeFileSync(
  TARGETS,
  `// Generated by scripts/sync-shared.ts — do not edit.
//
// What the person chose, by id, in their own wording. The reading stores the
// label beside a change, so a change always names the thing the person picked
// rather than the model's paraphrase of it.
//
// Ids are stored in the database and must never be renamed.

export const DIRECTION_AREA_LABELS: Record<string, string> = {
${entries(DIRECTION_AREAS.map((area) => [area.id, area.label] as const))}
};

export const DESIRED_SELF_LABELS: Record<string, string> = {
${entries(DESIRED_SELF_CARDS.map((card) => [card.id, card.label] as const))}
};
`
);
console.log(`generated ${TARGETS}`);
